#!/bin/bash
#
# This script checks to see if a port is open, if so we exit 0, if not, exit 1.
# We'll retry 5 times on fail to mitigate false alerts
# The purpose is to be a super lightweight "is this port open" command that
# can be ran on any linux box (no dep on netcat) against any host

if [ $# -lt 2 ]
then
  echo "There are 2 required arguments, host and port. Run the script like:"
  echo "./$0 hostname port"
  exit 0
fi

HOST=$1
PORT=$2

count=0
while :
  do
    timeout 2 bash -c "exec 3> /dev/tcp/${HOST}/${PORT} > /dev/null 2>&1"
    [[ $? = 0 ]] && exit 0 || ((count++))
       (( count >= 5 )) &&  exit 1
       sleep 5
    exit 1
done
